### ISSUE TITLE
9 - Categorize songs

### ISSUE THREAD

**Issue by CarlOfHoly** [1-fredrikstad/sangbok#12]
When organizing songs, I want the ability to categorize the songs from either predefined categories or create a new one. So that I can quickly find songs within a given category.

**Comment by KristofferNyvoll** [comment]
Kravet på denne job stoyen har endret seg over tid. Mulig at vi bare misforsto fra starten av. 
Uansett: det skal ikke gjøres noen sortering på kategori i frontenden. Det skal bare legges til ved opprettelse av sang, og vises i metadata-feltet til sangen
