### ISSUE TITLE
Swipe navigation only works on lyrics

### ISSUE THREAD

**Issue by Chaaarles** [1-fredrikstad/sangbok#64]
**Describe the bug**
Swiping to navigate between songs only reacts if you swipe on the song lyrics. 

**To Reproduce**
1. Go to any song
2. Swipe left or right beneath the lyrics
3. See that you do not go to the next/previous song

**Expected behavior**
Swiping should be enabled on the whole page, not only the lyrics

**Comment by Chaaarles** [comment]
Fixed

**Comment by Lekesoldat** [comment]
Ikke fikset likevel, må bare sette høyde på container og legge sweip der i stedet fo rpå tekst.
