### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by Chaaarles** [1-fredrikstad/sangbok#67]
**Describe the solution you'd like**
I think it would behoove us to add some more feedback and "tutorialized design" to navigation in the app.
At this time, users can swipe between songs, but this is never communicated to end users. 
Perhaps we could include some animations and navigation buttons to help onboard new users.

**Comment by kharann** [comment]
If all songs are available offline, this should be a thing!

**Comment by Chaaarles** [comment]
Minimum viable product: Arrow buttons clearly showing when there is/is not a next/previos song
