### ISSUE TITLE
Sviping funker ikke alltid

### ISSUE THREAD

**Issue by amunds1** [1-fredrikstad/sangbok#88]
**Describe the bug**
Sviping funker ikke alltid

**To Reproduce**
1. Go to /search
2. Click on a song
3. Try to swipe

**Expected behavior**
Svipingen funker

**Screenshots**

**Additional context**

**Comment by Chaaarles** [comment]
Spesifikt sveiping relatert til rekkefølge.

**Comment by CarlOfHoly** [comment]
Hvis man endrer rekkefølgen på sangene i Sanity Studio (under order documents) svært fort, så vil noen av sangene får samme indeks.

Løsning: Trykk på refresh pilene etter å ha endret på rekkefølgen. Da vil sanger som har fått feil indeks bli plassert et annet sted og alt fikser seg selv
