### ISSUE TITLE
Legg til appikon og logo i appen

### ISSUE THREAD

**Issue by kharann** [1-fredrikstad/sangbok#98]
We need to found a nice logo to use :)

**Comment by KristofferNyvoll** [comment]
![image](https://user-images.githubusercontent.com/43403179/115350349-4a24a480-a1b5-11eb-8620-3c693ad75da2.png)
![image](https://user-images.githubusercontent.com/43403179/115350372-4ee95880-a1b5-11eb-8605-a1b905e81953.png)
